### ISSUE TITLE
Stackdriver doesn't like validated_with_origin_server

### ISSUE THREAD

**Issue by wirtsi** [GoogleCloudPlatform/fluent-plugin-google-cloud#85]
Hi
I am trying to push Nginx logs in the httpRequest format so in GCE Logging I see the proper fields and not just one line per entry.

Log format is 
```
  log_format stackdriver '{"httpRequest":{ '
   '"remoteIp":"$remote_addr",'
   '"responseSize": "$bytes_sent",'
   '"status":"$status", '
   '"requestUrl": "$scheme://$host$request_uri",'
   '"requestMethod": "$request_method",'
   '"referer":"$http_referer",'
   '"requestSize":"$request_length",'
   '"userAgent":"$http_user_agent"}}';
```
Now when the log lines (which look like this btw)
```
{"httpRequest":{ "remoteIp":"109.44.1.129","responseSize": "56303","status":"200", "requestUrl": "http://tracking.foo.bar/piwik.js","requestMethod": "GET","referer":"https://tracking.foo.bar/url","requestSize":"574","userAgent":"Mozilla/5.0 (iPhone; CPU iPhone OS 9_2_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13D15 Safari/601.1"}}
```
hit the fluentd-gcp pod, the call to the logging API fails
```
016-09-20 11:42:13 +0000 [warn]: Dropping 7 log message(s) error_class="Google::Apis::ClientError" error="badRequest: Invalid JSON payload received. Unknown name \"validated_with_origin_server\" at 'entries[0].http_request': Cannot find field.\nInvalid JSON payload received. Unknown name \"validated_with_origin_server\" at 'entries[1].http_request': Cannot find field.
```
It doesn't make a difference if I actually set the validatedWithOriginServer field in the log format  or not.

It appears that the API doesn't like the validated_with_origin_server field at all (which gets created by the fluentd-plugin on line 699 (v0.5.2)). 

Uncommenting this line makes the logging work correctly, so I am not sure if this field doesn't get translated into cacheValidatedWithOriginServer (which by [this](https://cloud.google.com/logging/docs/api/ref/rest/v1beta3/projects.logs.entries/write) should be the correct name) or the API has changed

Bests

**Comment by mr-salty** [comment]
Hi - the API was changed but the google-api-ruby-client was not updated, nor was this plugin - sorry, the change kind of slipped through unnoticed until recently.  It is fixed in the current plugin (which uses the v2 API instead of v1) but that hasn't been released yet.  We weren't planning to backport it to v1; commenting it out is a good workaround assuming you don't actually care about the firled.

#84 is also related (which is why it happens even if you don't set it).

**Comment by razvanphp** [comment]
@mr-salty we tried today `gcr.io/google-containers/fluentd-gcp:2.0.2` and we still get this error:

```
2017-05-03 09:39:20 +0000 [warn]: Dropping 12 log message(s) error_class="Google::Apis::ClientError" error="badRequest: Invalid JSON payload received. Unknown name \"validated_with_origin_server\" at 'entries[0].http_request': Cannot find field.\nInvalid JSON payload received. Unknown name \"validated_with_origin_server\" at 'entries[1].http_request': Cannot find field.\nInvalid JSON payload received. Unknown name \"validated_with_origin_server\" at 'entries[2].http_request': Cannot find field.\nInvalid JSON payload received. Unknown name \"validated_with_origin_server\" at 'entries[3].http_request': Cannot find field.\nInvalid JSON payload received. Unknown name \"validated_with_origin_server\" at 'entries[4].http_request': Cannot find field.\nInvalid JSON payload received. Unknown name \"validated_with_origin_server\" at 'entries[5].http_request': Cannot find field.\nInvalid JSON payload received. Unknown name \"validated_with_origin_server\" at 'entries[6].http_request': Cannot find field.\nInvalid JSON payload received. Unknown name \"validated_with_origin_server\" at 'entries[7].http_request': Cannot find field.\nInvalid JSON payload received. Unknown name \"validated_with_origin_server\" at 'entries[8].http_request': Cannot find field.\nInvalid JSON payload received. Unknown name \"validated_with_origin_server\" at 'entries[9].http_request': Cannot find field.\nInvalid JSON payload received. Unknown name \"validated_with_origin_server\" at 'entries[10].http_request': Cannot find field.\nInvalid JSON payload received. Unknown name \"validated_with_origin_server\" at 'entries[11].http_request': Cannot find field."
```

What can be done to fix this?

**Comment by qingling128** [comment]
Hi @razvanphp,

The fix got released in [`v0.6.1`](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/releases/tag/v0.6.1). Seems [`fluentd-gcp:2.0.2`](https://github.com/kubernetes/contrib/blob/master/fluentd/fluentd-gcp-image/Gemfile#L6) still has version `0.5.*`, thus not picking up this fix.

A newer fluentd-gcp-image needs to be built to have this fix applied.

**Comment by qingling128** [comment]
https://github.com/kubernetes/contrib/issues/2579 created to build a new image.
